config/routes.rb
KwisatzMassive::Application.routes.draw do

  resources :links, :only => [ :new, :show, :create ]
  match "/:id" => "links#show", :as => :short_code
  root :to => "links#new"

end

app/models/link.rb
class Link < MassiveRecord::ORM::Table

  def self.new_id(url)
    Zlib.crc32(url).to_s(36)
  end

  column_family :core do
    field :link
  end
  
  column_family :meta do
    field :title
    field :summary
  end  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  respond_to :html, :json

  def create
    link = Link.create :id => Link.new_id(params[:link]), :link => params[:link]
    respond_with(link, :location => short_code_path(link.id))
  end

  def show
    @link = Link.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Kwisa.tz</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/links/new.html.erb
<h1>Shorten a link</h1>

<%= form_tag links_path  do %>
  <%= text_field_tag :link, nil, :size => 75  %>
  <br/>
  <%= submit_tag 'Shorten' %>
<% end %>

app/views/links/show.html.erb
<h1><%= @link.title%></h1>

<p>Click <%= link_to 'here', @link.link %> to redirect to <%= @link.link %></p>

<div>
  <%= @link.summary%>
</div>